Repository UMC-7th/Backend, pull requests merged in 2025-02, with the labels that each got.

#80 [FEAT] #79 식재료 북마크 조회
  build/index.cjs
  build/swagger.yaml
  src/controller/material.controller.ts
  src/repository/material.repository.ts
  src/routes/material.route.ts
  src/service/material.service.ts
Labels: :sparkles:feature

#82 [FEAT] #81 식재료 북마크 삭제
  build/index.cjs
  build/swagger.yaml
  src/controller/material.controller.ts
  src/repository/material.repository.ts
  src/routes/material.route.ts
  src/service/material.service.ts
Labels: :sparkles:feature

#86 [REFACTOR] #85 식단 난이도 int형으로 수정
  build/swagger.yaml
  package-lock.json
  prisma/schema.prisma
  src/dto/meal.dto.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
  src/util/jwt.util.ts
Labels: :recycle:refactor

#93 [REFACTOR] userId 토큰에서 추출
  build/swagger.yaml
  src/controller/meal.controller.ts
  src/dto/meal.dto.ts
  src/index.ts
  src/repository/meal.repository.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#94 [REFACOTR] #64 식단 추가 컨트롤러 로직 변경
  src/controller/meal.controller.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#91 [FEAT] #90 닉네임 저장 API 통합
  build/swagger.yaml
  src/routes/user.route.ts
Labels: :recycle:refactor

#99 [FEAT] 수동 추가 식단 삭제 api 구현
  build/swagger.yaml
  src/controller/meal.controller.ts
  src/repository/meal.repository.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :sparkles:feature

#103 [FEAT] #101 즐겨찾기 식단 조회
  build/swagger.yaml
  src/controller/meal.controller.ts
  src/repository/meal.repository.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :sparkles:feature

#107 [FEAT] #104 즐겨찾기 취소 api 구현
  build/swagger.yaml
  src/controller/meal.controller.ts
  src/repository/meal.repository.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :sparkles:feature

#108 [REFACOTR] 식단 생성 병렬 처리
  build/swagger.yaml
  src/controller/meal.controller.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#114 [FEAT] #69 유저 선호식단 gpt 요청에 담기
  build/swagger.yaml
  src/controller/meal.controller.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :sparkles:feature, :recycle:refactor

#117 [REFACTOR] #116 소셜 로그인 시 프로필 이미지 저장
  prisma/migrations/20250209045557_add_profile_image/migration.sql
  prisma/schema.prisma
  src/repository/user.repository.ts
Labels: :recycle:refactor

#118 [FEAT] #102 이미지 생성 중복 응답 처리
  build/swagger.yaml
  src/controller/image.controller.ts
  src/repository/image.repository.ts
  src/service/image.service.ts
Labels: :recycle:refactor

#120 [REFACTOR] #119 구독중인 식단 조회 url 변경
  build/swagger.yaml
  package-lock.json
  src/routes/subscribe.route.ts
Labels: :recycle:refactor

#122 [REFACTOR] #121 결제 시 subscribe 테이블에 저장
  src/repository/subscribe.repository.ts
  src/service/payment.service.ts
Labels: :recycle:refactor

#127 [FIX] #123 이미지 생성 동시성 제어
  src/controller/image.controller.ts
  src/service/image.service.ts
Labels: :bug:bug

#132 [FEAT] #129 식단 싫어요 api
  .github/workflows/deploy.yml
  build/swagger.yaml
  prisma/migrations/20250213113823_/migration.sql
  prisma/schema.prisma
  src/controller/dummy.controller.ts
  src/controller/meal.controller.ts
  src/index.ts
  src/repository/meal.repository.ts
  src/routes/meal.route.ts
  src/service/dummy.service.ts
  src/service/meal.service.ts
Labels: :sparkles:feature

#135 [REFACTOR] #133 즐겨찾기 식단 칼로리순 조회
  package-lock.json
  src/repository/meal.repository.ts
Labels: :recycle:refactor

#140 [REFACTOR] #139 updateImage함수 리팩토링
  src/controller/mypage.controller.ts
Labels: :recycle:refactor

#142 [FEAT] #141 즐겨찾기 식단 최신순 조회
  build/swagger.yaml
  src/controller/meal.controller.ts
  src/repository/meal.repository.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :sparkles:feature

#146 식단 완료 리팩토링
  src/controller/meal.controller.ts
  src/dto/meal.dto.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#148 [REFACTOR] #145 식단 수동 추가 리팩토링
  src/controller/meal.controller.ts
  src/dto/meal.dto.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#149 [REFACTOR] #147 식단 생성 리팩토링
  src/controller/meal.controller.ts
  src/dto/meal.dto.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#154 [REFACTOR] #150 식단 재생성 리팩토링
  src/controller/meal.controller.ts
  src/dto/meal.dto.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#155 [REFACTOR] #151 수동 식단 api 리팩토링
  src/controller/meal.controller.ts
  src/dto/meal.dto.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#156 [REFACTOR] #144 식단 즐겨찾기 api 리팩토링
  src/controller/meal.controller.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#158 [REFACTOR] #157 함수 재배치
  src/controller/meal.controller.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#159 [REFACTOR] #152 식단 싫어요 api 리팩토링
  src/controller/meal.controller.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#162 [REFACTOR] #160 식단 좋아요 리팩토링
  src/controller/meal.controller.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#163 [REFACTOR] #161 구독 식단 api 리팩토링
  src/controller/meal.controller.ts
  src/controller/subscribe.meal.controller.ts
  src/dto/meal.dto.ts
  src/dto/subscribe.meal.dto.ts
  src/repository/subscribe.meal.repository.ts
  src/routes/subscribe.meal.route.ts
  src/service/meal.service.ts
  src/service/subscribe.meal.service.ts
Labels: :recycle:refactor

#164 [REFACTOR] #153 스웨거 수정
  build/swagger.yaml
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#166 [REFACTOR] mypage route 리팩토링
  src/controller/mypage.controller.ts
Labels: :recycle:refactor

#168 [REFACTOR] mypage 서비스 리팩토링
  src/service/mypage.service.ts
Labels: :recycle:refactor

#170 [FEAT] #169 식단 기본 이미지 설정
  src/controller/image.controller.ts
Labels: :sparkles:feature

#173 [FEAT] #171 건강점수 기본값 할당
  src/service/mypage.service.ts
Labels: :sparkles:feature

#174 [FEAT] 식단 api 동시성 제어
  src/controller/meal.controller.ts
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :sparkles:feature

#177 [REFACTOR] #176 식단 상세 조회 응답 수정
  build/swagger.yaml
  src/service/meal.service.ts
Labels: :recycle:refactor

#179 [REFACTOR] #178 구독 식단 상세 조회 응답값 수정
  build/swagger.yaml
  src/repository/subscribe.meal.repository.ts
  src/service/subscribe.meal.service.ts
Labels: :recycle:refactor

#181 [FEAT] #175 동시성 제어
  package-lock.json
  package.json
  src/service/mypage.service.ts
Labels: :sparkles:feature

#182 [FEAT] #180 장바구니 리스트 API 구현
  src/controller/subscribe.controller.ts
  src/repository/subscribe.repository.ts
  src/routes/subscribe.route.ts
  src/service/subscribe.service.ts
Labels: :sparkles:feature

#186 [FEAT] #185 식재료 품종 검색 구현
  build/swagger.yaml
  src/controller/material.controller.ts
  src/repository/material.repository.ts
  src/routes/material.route.ts
  src/service/material.service.ts
Labels: :sparkles:feature

#188 [FEAT] #187 전체 식재료 랭킹 조회 구현
  build/swagger.yaml
  src/controller/material.controller.ts
  src/repository/material.repository.ts
  src/routes/material.route.ts
  src/service/material.service.ts
Labels: :sparkles:feature

#190 [FEAT] #189 품종별 식재료 랭킹 조회 구현
  build/swagger.yaml
  src/controller/material.controller.ts
  src/repository/material.repository.ts
  src/routes/material.route.ts
  src/service/material.service.ts
Labels: :sparkles:feature

#194 [FIX] #193 식재료 랭킹 기준 수정
  build/swagger.yaml
  src/controller/material.controller.ts
  src/repository/material.repository.ts
  src/service/material.service.ts
Labels: :hammer: fix

#196 [REFACOTR] #195 식단 상세 조회 응답 수정
  build/swagger.yaml
  package-lock.json
  src/repository/meal.repository.ts
  src/repository/subscribe.meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor
