Repository UMC-7th/Backend, pull requests merged in 2025-01, with the labels that each got.

#2 [FEAT] #1 Swagger 기초 설정
  build/swagger.yaml
  package-lock.json
  package.json
  src/index.js
  src/swagger/openapi.yaml
Labels: :sparkles:feature

#11 [FEAT] #7 gpt에게 하루 식단 받아오기 api 구현
  package-lock.json
  package.json
  src/controller/diet.controller.ts
  src/controller/dummy.controller.ts
  src/dto/diet.dto.ts
  src/dto/dummy.dto.ts
  src/index.ts
  src/repository/diet.repository.ts
  src/routes/diet.route.ts
  src/routes/index.ts
  src/service/diet.service.ts
  src/service/dummy.service.ts
Labels: :sparkles:feature

#14 [FEAT] #13 프리스마 모델 세팅 완료
  package-lock.json
  package.json
  prisma/migrations/20250115191006_init_database/migration.sql
  prisma/migrations/20250116055448_/migration.sql
  prisma/migrations/20250116065809_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/index.ts
  src/routes/index.route.ts
Labels: :sparkles:feature

#16 [FEAT] #10 음식 이미지 생성
  build/index.cjs
  build/swagger.yaml
  package.json
  prisma/migrations/20250116125210_add_image_food_domain/migration.sql
  prisma/migrations/20250116135833_drop_image_food/migration.sql
  prisma/migrations/20250116135914_recreate_image_food/migration.sql
  prisma/schema.prisma
  src/controller/image.controller.ts
  src/repository/image.repository.ts
  src/routes/image.route.ts
  src/routes/index.route.ts
  src/service/image.service.ts
  src/swagger/openapi.yaml
  src/util/error.ts
Labels: :sparkles:feature

#20 [FEAT] #17 signup login api 구현
  package-lock.json
  package.json
  src/config/passport.ts
  src/controller/user.controller.ts
  src/dto/user.dto.ts
  src/index.ts
  src/repository/user.repository.ts
  src/routes/index.route.ts
  src/routes/user.route.ts
  src/service/user.service.ts
Labels: :sparkles:feature

#21 [FEAT] #15 식단데이터 생성 및 저장 api 구현
  src/controller/diet.controller.ts
  src/controller/meal.controller.ts
  src/dto/diet.dto.ts
  src/dto/meal.dto.ts
  src/repository/diet.repository.ts
  src/repository/dummy.repository.ts
  src/repository/meal.repository.ts
  src/repository/user.repository.ts
  src/routes/diet.route.ts
  src/routes/index.route.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :sparkles:feature

#23 [FEAT] #22 네이버 로그인 api 구현
  package-lock.json
  package.json
  src/config/passport.ts
  src/index.ts
  src/repository/user.repository.ts
  src/service/user.service.ts
Labels: :sparkles:feature

#25 [FEAT] #18 식단 이미지 생성
  build/index.cjs
  build/swagger.yaml
  package-lock.json
  package.json
  src/controller/image.controller.ts
  src/dto/image.dto.ts
  src/repository/image.repository.ts
  src/routes/image.route.ts
  src/service/image.service.ts
Labels: :sparkles:feature

#30 [FEAT] #26 schema 변경
  build/swagger.yaml
  prisma/migrations/20250124080726_drop_all_table/migration.sql
  prisma/migrations/20250124080826_recreate_all_table/migration.sql
  prisma/migrations/20250124081103_rename_table/migration.sql
  prisma/schema.prisma
  src/dto/user.dto.ts
  src/repository/image.repository.ts
  src/repository/meal.repository.ts
  src/repository/user.repository.ts
  src/service/meal.service.ts
Labels: :sparkles:feature, :recycle:refactor

#32 [FEAT] #31 JWT 인증 방식으로 변경
  build/swagger.yaml
  package-lock.json
  package.json
  prisma/migrations/20250125095030_add_nickname_column/migration.sql
  prisma/schema.prisma
  src/config/passport.ts
  src/controller/user.controller.ts
  src/index.ts
  src/repository/user.repository.ts
  src/routes/user.route.ts
  src/service/user.service.ts
  src/util/jwt.middleware.ts
  src/util/jwt.util.ts
Labels: :sparkles:feature, :recycle:refactor

#42 [FEAT] #34 배송지 정보 작성
  @types/environment.d.ts
  build/index.cjs
  build/swagger.yaml
  prisma/migrations/20250127084737_edit_table_delivery_address/migration.sql
  prisma/schema.prisma
  src/controller/deliveryAddress.controller.ts
  src/dto/deliveryAddress.dto.ts
  src/repository/deliveryAddress.repository.ts
  src/routes/deliveryAddress.route.ts
  src/routes/index.route.ts
  src/service/deliveryAddress.service.ts
  src/util/jwt.middleware.ts
Labels: :sparkles:feature

#44 [FEAT] #43 배송지 정보 조회
  build/index.cjs
  build/swagger.yaml
  src/controller/deliveryAddress.controller.ts
  src/repository/deliveryAddress.repository.ts
  src/routes/deliveryAddress.route.ts
  src/routes/index.route.ts
  src/service/deliveryAddress.service.ts
Labels: :sparkles:feature

#46 [FEAT] #45 배송지 정보 수정
  build/index.cjs
  build/swagger.yaml
  src/controller/deliveryAddress.controller.ts
  src/dto/deliveryAddress.dto.ts
  src/repository/deliveryAddress.repository.ts
  src/routes/deliveryAddress.route.ts
  src/service/deliveryAddress.service.ts
Labels: :sparkles:feature

#48 [FEAT] #47 기본 배송지 설정
  build/index.cjs
  build/swagger.yaml
  src/controller/deliveryAddress.controller.ts
  src/repository/deliveryAddress.repository.ts
  src/routes/deliveryAddress.route.ts
  src/service/deliveryAddress.service.ts
Labels: :sparkles:feature

#50 [FEAT] #49 기본 배송지 조회
  build/index.cjs
  build/swagger.yaml
  src/controller/deliveryAddress.controller.ts
  src/repository/deliveryAddress.repository.ts
  src/routes/deliveryAddress.route.ts
  src/service/deliveryAddress.service.ts
Labels: :sparkles:feature

#53 Feature/33/diet api
  src/controller/meal.controller.ts
  src/repository/meal.repository.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
  src/util/middleware.ts
Labels: :sparkles:feature

#56 [REFACTOR] 하루 식단 조회 api 수정
  src/repository/meal.repository.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#58 [FEAT] #57 식단 수동 추가 및 조회
  prisma/migrations/20250129154301_/migration.sql
  prisma/schema.prisma
  src/controller/meal.controller.ts
  src/dto/meal.dto.ts
  src/repository/meal.repository.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :sparkles:feature

#61 [FEAT] 식단 api 스웨거 작성
  build/swagger.yaml
  src/dto/deliveryAddress.dto.ts
  src/dto/meal.dto.ts
  src/repository/meal.repository.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :sparkles:feature

#66 [REFACTOR] #62 req.body를 req.query로 수정
  build/swagger.yaml
  src/controller/meal.controller.ts
  src/routes/meal.route.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#68 [REFACTOR] #63 gpt 프롬프트 변경
  src/repository/meal.repository.ts
  src/service/meal.service.ts
Labels: :recycle:refactor

#70 [FEAT] #51 구독 내역 캘린더형 조회
  build/index.cjs
  build/swagger.yaml
  src/controller/subscribe.controller.ts
  src/repository/subscribe.repository.ts
  src/routes/index.route.ts
  src/routes/subscribe.route.ts
  src/service/subscribe.service.ts
Labels: :sparkles:feature

#67 [FEAT] #52 식단 장바구니 추가 및 제거
  build/swagger.yaml
  src/controller/subscribe.controller.ts
  src/dto/subscribe.dto.ts
  src/repository/subscribe.repository.ts
  src/routes/subscribe.route.ts
  src/service/subscribe.service.ts
Labels: :sparkles:feature

#72 [FEAT] #71 구독 목록 리스트형 조회
  build/index.cjs
  build/swagger.yaml
  prisma/migrations/20250130072302_set_subsribe_column/migration.sql
  prisma/schema.prisma
  src/controller/subscribe.controller.ts
  src/repository/subscribe.repository.ts
  src/routes/subscribe.route.ts
  src/service/subscribe.service.ts
Labels: :sparkles:feature

#60 [FEAT] #28 회원 탈퇴 API
  build/index.cjs
  build/swagger.yaml
  prisma/schema.prisma
  src/controller/mypage.controller.ts
  src/controller/user.controller.ts
  src/dto/mypage.dto.ts
  src/repository/mypage.repository.ts
  src/routes/mypage.route.ts
  src/service/mypage.service.ts
Labels: :sparkles:feature

#73 Feature/35/payment api
  package-lock.json
  package.json
  src/controller/payment.controller.ts
  src/dto/payment.dto.ts
  src/routes/index.route.ts
  src/routes/payment.route.ts
  src/service/payment.service.ts
Labels: :sparkles:feature

#76 [FEAT] #75 구독 내역 검색
  build/index.cjs
  build/swagger.yaml
  src/controller/subscribe.controller.ts
  src/repository/subscribe.repository.ts
  src/routes/subscribe.route.ts
  src/service/subscribe.service.ts
Labels: :sparkles:feature
